project_id = "tdxychpgxptgxqvqiedj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MB"
public_url = "http://127.0.0.1:54321/storage/v1"

[auth]
enabled = true
site_url = "https://lovely-salamander-a3df8b.netlify.app/"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false
minimum_password_length = 6
enable_email_autoconfirm = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
secure_email_change_enabled = false
secure_password_change_enabled = false

# Prevent duplicate signups
[auth.sessions]
timebox = 24
inactivity_timeout = 8

# Payment processing edge functions
[functions.create-stripe-payment]
verify_jwt = false

[functions.create-paypal-payment] 
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-order]
verify_jwt = true

[functions.verify-newsletter-subscription]
verify_jwt = false

[functions.secure-newsletter-signup]
verify_jwt = false

[functions.submit-contact-message]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.delete-account]
verify_jwt = true