import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'he';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.courses': 'Courses',
    'nav.wrapping': 'Car Wrapping',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Premium Car Care & Training Solutions',
    'hero.subtitle': 'Official Koch-Chemie distributor offering professional detailing products, expert training courses, and premium car wrapping services.',
    'hero.cta.products': 'Shop Products',
    'hero.cta.courses': 'View Courses',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive Car Care solutions from products to training to premium wrapping services',
    'services.koch_title': 'Koch-Chemie Products',
    'services.koch_description': 'Professional-grade car care products from Germany\'s leading manufacturer.',
    'services.koch_features.1': 'Premium car care',
    'services.koch_features.2': 'Professional detailing',
    'services.koch_features.3': 'Industry-leading quality',
    'services.koch_cta': 'View Products',
    'services.courses_title': 'Detailing Courses',
    'services.courses_description': 'Expert training programs for professional car detailing and polishing techniques.',
    'services.courses_features.1': 'Hands-on training',
    'services.courses_features.2': 'Online & in-person',
    'services.courses_features.3': 'Certification included',
    'services.courses_cta': 'Enroll Today',
    'services.wrapping_title': 'MT Wraps Services',
    'services.wrapping_description': 'Premium car wrapping and vinyl installation services for a stunning finish.',
    'services.wrapping_features.1': 'Custom designs',
    'services.wrapping_features.2': 'Premium materials',
    'services.wrapping_features.3': 'Expert installation',
    'services.wrapping_cta': 'View Gallery',

    // Gallery/Wrapping Page
    'gallery.title': 'Professional Vehicle Wrapping',
    'gallery.subtitle': 'Transform your vehicle with premium automotive films. From complete color changes to protective solutions, we deliver exceptional results with industry-leading materials.',
    'gallery.services_title': 'Our Wrapping Services',
    'gallery.services_subtitle': 'Contact us to discuss your needs from our variety of professional vehicle wrapping and detailing services',
    'gallery.professional_title': 'Professional Vehicle Services',
    'gallery.professional_description': 'We offer a comprehensive range of vehicle wrapping and detailing services. Contact us to discuss which service best fits your needs and budget.',
    'gallery.wrapping_services': 'Wrapping Services',
    'gallery.additional_services': 'Additional Services',
    'gallery.why_choose': 'Why Choose Our Services?',
    'gallery.premium_materials': 'Premium Materials',
    'gallery.premium_materials_desc': 'Industry-leading automotive films',
    'gallery.expert_installation': 'Expert Installation',
    'gallery.expert_installation_desc': 'Professional certified technicians',
    'gallery.quality_guarantee': 'Quality Guarantee',
    'gallery.quality_guarantee_desc': 'Warranty on all services',
    'gallery.contact_quote': 'Ready to transform your vehicle? Contact us to discuss your project and get a personalized quote.',
    'gallery.contact_for_quote': 'Contact for Quote',
    'gallery.request_consultation': 'Request Consultation',

    // About Page
    'about.badge': 'About MT Wraps',
    'about.title': 'Crafting Excellence in Automotive Care',
    'about.subtitle': 'Official Koch-Chemie distribution partner bringing world-class German car care products and professional expertise directly to you.',
    'about.story_title': 'Our Story',
    'about.story_p1': 'We are proud to be an official Koch-Chemie distribution partner, bringing world-class German car care products directly to professionals and enthusiasts across the region.',
    'about.story_p2': 'With years of hands-on experience in detailing, polishing, and surface treatment, we don\'t just sell products — we live the craft. Our deep understanding of the industry allows us to provide tailored solutions for every stage of vehicle care, from pre-wash to final finish.',
    'about.story_p3': 'We are also the founders of MT Wraps, one of the leading names in high-quality vehicle wrapping and customization. Our work speaks for itself — precision, creativity, and premium execution on every car we touch.',
    'about.koch_partner': 'Koch-Chemie Official Partner',
    'about.koch_desc': 'Since 1968, Koch-Chemie has been the benchmark for professional car care. As their official partner, we bring you authentic German engineering excellence.',
    'about.achievements': 'Key Achievements',
    'about.achievement_1': 'Official Koch-Chemie Partner',
    'about.achievement_1_desc': 'Authorized distributor of premium German car care products',
    'about.achievement_2': '500+ Satisfied Clients',
    'about.achievement_2_desc': 'Serving professionals and enthusiasts across the region',
    'about.achievement_3': 'Professional Training',
    'about.achievement_3_desc': 'Comprehensive detailing and polishing courses',
    'about.achievement_4': 'MT Wraps Expertise',
    'about.achievement_4_desc': 'Leading vehicle wrapping and customization services',
    'about.values_title': 'Our Values',
    'about.value_precision': 'Precision',
    'about.value_precision_desc': 'Every detail matters in our work and service delivery',
    'about.value_innovation': 'Innovation',
    'about.value_innovation_desc': 'Staying ahead with cutting-edge products and techniques',
    'about.value_quality': 'Quality',
    'about.value_quality_desc': 'Only the finest German-engineered products and materials',
    'about.value_education': 'Education',
    'about.value_education_desc': 'Empowering professionals through knowledge and training',
    
    // Contact Page
    'contact.badge': 'Get In Touch',
    'contact.title': 'Contact MT Wraps',
    'contact.subtitle': 'Ready to elevate your vehicle care? Get in touch with our team for products, training, or professional wrapping services.',
    'contact.form_title': 'Send us a Message',
    'contact.form_subtitle': 'Fill out the form below and we\'ll get back to you within 24 hours',
    'contact.name': 'Full Name',
    'contact.name_placeholder': 'Enter your full name',
    'contact.email': 'Email Address',
    'contact.email_placeholder': 'Enter your email address',
    'contact.phone': 'Phone Number',
    'contact.phone_placeholder': 'Enter your phone number',
    'contact.company': 'Company',
    'contact.company_placeholder': 'Enter your company name',
    'contact.service_interest': 'Service Interest',
    'contact.service_interest_placeholder': 'Select a service',
    'contact.subject': 'Subject',
    'contact.subject_placeholder': 'Brief subject of your inquiry',
    'contact.message': 'Message',
    'contact.message_placeholder': 'Tell us about your needs...',
    'contact.send_message': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.info_title': 'Contact Information',
    'contact.phone_title': 'Phone',
    'contact.phone_desc': 'Call us during business hours',
    'contact.email_title': 'Email',
    'contact.email_desc': 'We respond within 24 hours',
    'contact.location_title': 'Location',
    'contact.location_desc': 'Visit our showroom and workshop',
    'contact.hours_title': 'Business Hours',
    'contact.hours_desc': 'Sunday to Thursday, contact for specific times',
    'contact.success_title': 'Message Sent Successfully!',
    'contact.success_desc': 'We\'ll get back to you within 24 hours.',
    'contact.error_title': 'Error',
    'contact.error_desc': 'Failed to send message. Please try again.',
    
    // Products Page  
    'products.all_categories': 'All Categories',
    'products.view_details': 'View Details',
    'products.add_to_cart': 'Add to Cart',
    'products.in_stock': 'In Stock',
    'products.out_of_stock': 'Out of Stock',
    'products.price_tba': 'TBA',
    'products.price_coming_soon': 'Price Coming Soon',
    'products.lowest_price': 'From',
    'products.select_variant': 'Select Variant',
    'products.back_to_products': 'Back to Products',
    
    // Footer
    'footer.company_name': 'MTKcx',
    'footer.company_desc': 'Official Koch-Chemie distributor providing premium car care products, professional training, and expert wrapping services.',
    'footer.quick_links': 'Quick Links',
    'footer.services': 'Services',
    'footer.service_1': 'Professional Car Care',
    'footer.service_2': 'Detailing Training',
    'footer.service_3': 'Car Wrapping',
    'footer.service_4': 'Product Distribution',
    'footer.copyright': '© 2025 MT Wraps. All rights reserved. | Koch-Chemie',
    
    // Stats
    'stats.products': 'Premium Products',
    'stats.customers': 'Happy Customers',
    'stats.experience': 'Years Experience',

    // Products
    'products.title': 'Koch-Chemie Product Catalog',
    'products.subtitle': 'Discover our complete range of professional automotive detailing products. Each product is available in multiple sizes to meet your specific needs.',
    'products.search_placeholder': 'Search products by name, description, or product code...',
    'products.filters': 'Filters',
    'products.showing_results': 'Showing {count} of {total} products',
    'products.clear_filters': 'Clear filters',
    'products.clear_all_filters': 'Clear all filters',
    'products.no_products': 'No products found matching your criteria.',
    'products.loading': 'Loading...',

    // Common
    'common.learn_more': 'Learn More',
    'common.contact_us': 'Contact Us',
    'common.get_started': 'Get Started',
    'common.search': 'Search',
    'common.professional_training': 'Professional Training',
    'common.mt_wraps_services': 'MT Wraps Services',
    'common.official_partner': 'Official Koch-Chemie Partner',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.view_all': 'View All',
    'common.show_more': 'Show More',
    'common.show_less': 'Show Less',
    'common.read_more': 'Read More',
    'common.visit_us': 'Visit Us',
    'common.enrollment_interest': 'Enrollment Interest Received!',
    'common.contact_course_info': 'We\'ll contact you about the Koch Chemie Professional Detailing & Polishing Certification within 24 hours.',
    'common.get_course_info': 'Get Course Information',
    'common.koch_official_training': 'Koch Chemie Official Training',
    'common.only_official_course': 'This is the only official Koch Chemie certification course in the region. Upon completion, you\'ll be a certified Koch Chemie professional detailer.',
    'common.quote_request_received': 'Quote Request Received!',
    'common.contact_service_hours': 'We\'ll contact you about {service} within 24 hours.',
    'common.beyond_products': 'Beyond Products - Education & Excellence',
    'common.why_choose_mt': 'Why Choose MT Wraps?',
    'common.professional_training_programs': 'Professional Training Programs',
    'common.expert_wrapping_services': 'Expert Wrapping Services',
    'common.fast_response_time': 'Fast Response Time',
    'common.our_work_gallery': 'Our Work Gallery',
    'common.explore_portfolio': 'Explore our portfolio of vehicle transformations and custom projects',
    'common.project_gallery_image': 'Project Gallery Image',
    'common.images_coming_soon': '(Images coming soon)',
    'common.view_full_gallery': 'View Full Gallery',
    'common.ready_transform_vehicle': 'Ready to Transform Your Vehicle?',
    'common.contact_consultation': 'Contact us today for a personalized consultation and quote for your vehicle wrapping project.',
    'common.call_for_quote': 'Call for Quote',
    'common.schedule_consultation': 'Schedule Consultation',
    // About page specific
    'about.our_achievements': 'Our Achievements',
    'about.building_trust': 'Building trust through excellence, innovation, and unwavering commitment to quality',
    'about.services_array_1': 'Official Koch-Chemie product distribution',
    'about.services_array_2': 'Professional detailing and polishing training',
    'about.services_array_3': 'Premium vehicle wrapping services',
    'about.services_array_4': 'Custom car care solutions',
    'about.services_array_5': 'Technical support and consultation',
    'about.services_array_6': 'Industry-leading surface treatments',
    'about.beyond_sales': 'Beyond product sales, we are committed to education and excellence. That\'s why we offer intensive detailing and polishing courses, combining theory and hands-on experience to help professionals raise their standards and deliver top-tier results.',
    'about.koch_certification': 'Koch Chemie Official Certification',
    'about.hands_on_training': 'Hands-on training methods',
    'about.industry_experts': 'Industry expert instructors',
    'about.mt_wraps_service': 'MT Wraps Services',
    'about.wraps_excellence': 'Our MT Wraps division represents the pinnacle of vehicle customization. From concept to completion, we deliver stunning transformations that protect and enhance your vehicle\'s appearance with precision craftsmanship.',
    'about.custom_designs': 'Custom design solutions',
    'about.premium_materials': 'Premium 3M & Avery materials',
    'about.expert_installation': 'Expert installation team',
    // Contact page specific - additional translations
    'contact.get_in_touch_badge': 'Get In Touch',
    'contact.contact_mt_wraps_title': 'Contact MT Wraps',
    'contact.ready_elevate_subtitle': 'Ready to elevate your automotive care experience? Get in touch with our expert team for products, training, or professional wrapping services.',
    'contact.send_message_title': 'Send us a Message',
    'contact.fill_form_subtitle': 'Fill out the form below and we\'ll get back to you as soon as possible.',
    'contact.full_name_label': 'Full Name *',
    'contact.enter_full_name_placeholder': 'Enter your full name',
    'contact.email_address_label': 'Email Address *',
    'contact.email_placeholder_alt': 'your.email@example.com',
    'contact.phone_number_label': 'Phone Number',
    'contact.company_name_label': 'Company',
    'contact.your_business_placeholder': 'Your business name',
    'contact.service_of_interest_label': 'Service of Interest',
    'contact.select_service_option': 'Select a service...',
    'contact.brief_description_placeholder': 'Brief description of your inquiry',
    'contact.business_hours_info': 'Business Hours',
    'contact.sunday_thursday_hours': 'Sunday - Thursday: 10:00 AM - 6:00 PM',
    'contact.fridays_off_note': 'Fridays are off',
    'contact.atarot_location_address': 'Atarot Industrial Area, Hatamrukim, Jerusalem',
    'contact.visit_showroom_desc': 'Visit our showroom and workshop',
    'contact.call_business_hours_desc': 'Call us during business hours',
    'contact.respond_24_hours_desc': 'We respond within 24 hours',
    'contact.failed_send_error': 'Failed to send message. Please try again.',
    // Service options
    'contact.koch_products_option': 'Koch-Chemie Products',
    'contact.detailing_training_option': 'Detailing Training',
    'contact.vehicle_wrapping_option': 'Vehicle Wrapping',
    'contact.professional_consultation_option': 'Professional Consultation',
    'contact.other_services_option': 'Other Services',
    
    // Courses Page
    'courses.title': 'Professional Detailing & Polishing Certification',
    'courses.subtitle': 'Master the art of automotive detailing with Koch Chemie professional products and techniques. Get certified by industry experts.',
    'courses.intro_title': 'Course Introduction',
    'courses.intro_subtitle': 'Learn what you\'ll accomplish in this comprehensive training program',
    'courses.course_title': 'Professional Detailing & Polishing Certification',
    'courses.course_description': 'A comprehensive 4-day certification program designed to teach professional automotive detailing and polishing techniques using Koch Chemie products.',
    'courses.professional_certification': 'Professional Certification Course',
    'courses.interactive_training': '4-Day Interactive & Hands-On Training',
    'courses.contact_pricing': 'Contact for Pricing',
    'courses.includes_certification': 'Includes certification',
    'courses.what_learn': 'What You\'ll Learn',
    'courses.course_structure': '4-Day Course Structure',
    'courses.why_choose': 'Why Choose Our Koch Chemie Certification?',
    'courses.course_includes': 'Course Includes:',
    'courses.enroll_now': 'Enroll Now',
    'courses.contact_details': 'Contact for Details',
    'courses.training_schedule': 'Training Schedule',
    'courses.ready_certified': 'Ready to Get Certified?',
    'courses.contact_training': 'Contact us to discuss your training needs and reserve your spot in our next certification course',
    'courses.call_us': 'Call Us',
    'courses.email_us': 'Email Us',
    'courses.course_duration': 'Course Duration:',
    'courses.training_format': 'Training Format:',
    'courses.class_size': 'Class Size:',
    'courses.location': 'Location:',
    'courses.training_hours': 'Training Hours:',
    'courses.next_dates': 'Next Available Dates:',
    'courses.contact_schedule': 'Contact us to schedule your preferred training dates. We accommodate both individual and group bookings with flexible scheduling.',
    // Learning items
    'courses.professional_techniques': 'Professional detailing techniques and methodologies',
    'courses.advanced_polishing': 'Advanced polishing methods and compound applications',
    'courses.product_knowledge': 'Koch Chemie product knowledge and proper usage',
    'courses.paint_correction': 'Paint correction and restoration techniques',
    'courses.surface_assessment': 'Surface assessment and defect analysis',
    'courses.machine_polishing': 'Machine polishing mastery (rotary & dual-action)',
    'courses.quality_control': 'Quality control and finishing techniques',
    'courses.business_practices': 'Business practices and customer service excellence',
    // Course structure
    'courses.day_1': 'Day 1: Fundamentals',
    'courses.day_1_desc': 'Koch Chemie product knowledge, surface analysis, and basic detailing techniques',
    'courses.day_2': 'Day 2: Advanced Detailing',
    'courses.day_2_desc': 'Interior/exterior detailing mastery, protection applications, and quality standards',
    'courses.day_3': 'Day 3: Polishing Mastery',
    'courses.day_3_desc': 'Paint correction, compound techniques, machine operation, and defect removal',
    'courses.day_4': 'Day 4: Certification',
    'courses.day_4_desc': 'Practical assessment, final projects, and official Koch Chemie certification',
    // Why choose
    'courses.official_certification': 'Official Certification',
    'courses.recognized_cert': 'Recognized Koch Chemie certification',
    'courses.expert_instructors': 'Expert Instructors',
    'courses.certified_professionals': 'Certified Koch Chemie professionals',
    'courses.interactive_hands_on': 'Interactive & Hands-On',
    'courses.practical_training': 'Real-world practical training',
    // Course includes
    'courses.product_kit': 'Complete Koch Chemie product kit',
    'courses.equipment_access': 'Professional polishing equipment access',
    'courses.training_materials': 'All training materials and documentation',
    'courses.practice_vehicles': 'Practice vehicles for hands-on training',
    'courses.certification_included': 'Official Koch Chemie certification',
    'courses.lunch_refreshments': 'Lunch and refreshments all 4 days',
    'courses.digital_materials': 'Digital course materials and resources',
    'courses.post_support': 'Post-course support and guidance',
    // Schedule details
    'courses.four_days': '4 Days',
    'courses.interactive_format': 'Interactive & Hands-On',
    'courses.small_groups': 'Small Groups (Max 5)',
    'courses.atarot_location': 'Atarot Industrial Area, Jerusalem',
    'courses.tba': 'To be announced',
    'courses.course_intro_video': 'Course Introduction Video',
    'courses.video_placeholder': 'Replace this placeholder with your video embed',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.courses': 'الدورات',
    'nav.wrapping': 'تغليف السيارات',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    
    // Hero Section
    'hero.title': 'حلول العناية بالسيارات والتدريب المتميزة',
    'hero.subtitle': 'الموزع الرسمي لكوخ كيمي يقدم منتجات التنظيف المهنية ودورات التدريب المتخصصة وخدمات تغليف السيارات المتميزة.',
    'hero.cta.products': 'تسوق المنتجات',
    'hero.cta.courses': 'عرض الدورات',
    
    // Services Section
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول شاملة للعناية بالسيارات من المنتجات إلى التدريب وخدمات التغليف المتميزة',
    'services.koch_title': 'منتجات كوخ كيمي',
    'services.koch_description': 'منتجات العناية بالسيارات الاحترافية من الشركة الرائدة في ألمانيا.',
    'services.koch_features.1': 'العناية المتميزة بالسيارات',
    'services.koch_features.2': 'التنظيف المهني',
    'services.koch_features.3': 'جودة رائدة في الصناعة',
    'services.koch_cta': 'عرض المنتجات',
    'services.courses_title': 'دورات التنظيف',
    'services.courses_description': 'برامج تدريبية متخصصة لتقنيات تنظيف وتلميع السيارات المهنية.',
    'services.courses_features.1': 'تدريب عملي',
    'services.courses_features.2': 'عبر الإنترنت وشخصياً',
    'services.courses_features.3': 'يشمل الشهادة',
    'services.courses_cta': 'سجل اليوم',
    'services.wrapping_title': 'خدمات إم تي رابس',
    'services.wrapping_description': 'خدمات تغليف السيارات المتميزة وتركيب الفينيل للحصول على إطلالة مذهلة.',
    'services.wrapping_features.1': 'تصاميم مخصصة',
    'services.wrapping_features.2': 'مواد متميزة',
    'services.wrapping_features.3': 'تركيب احترافي',
    'services.wrapping_cta': 'عرض المعرض',

    // Gallery/Wrapping Page
    'gallery.title': 'تغليف السيارات المهني',
    'gallery.subtitle': 'حوّل سيارتك باستخدام أفلام السيارات المتميزة. من تغييرات الألوان الكاملة إلى حلول الحماية، نقدم نتائج استثنائية بمواد رائدة في الصناعة.',
    'gallery.services_title': 'خدمات التغليف لدينا',
    'gallery.services_subtitle': 'اتصل بنا لمناقشة احتياجاتك من مجموعة متنوعة من خدمات تغليف السيارات والتنظيف المهنية',
    'gallery.professional_title': 'خدمات السيارات المهنية',
    'gallery.professional_description': 'نقدم مجموعة شاملة من خدمات تغليف السيارات والتنظيف. اتصل بنا لمناقشة الخدمة التي تناسب احتياجاتك وميزانيتك.',
    'gallery.wrapping_services': 'خدمات التغليف',
    'gallery.additional_services': 'خدمات إضافية',
    'gallery.why_choose': 'لماذا تختار خدماتنا؟',
    'gallery.premium_materials': 'مواد متميزة',
    'gallery.premium_materials_desc': 'أفلام السيارات الرائدة في الصناعة',
    'gallery.expert_installation': 'تركيب احترافي',
    'gallery.expert_installation_desc': 'فنيون محترفون معتمدون',
    'gallery.quality_guarantee': 'ضمان الجودة',
    'gallery.quality_guarantee_desc': 'ضمان على جميع الخدمات',
    'gallery.why_choose_wrapping': 'لماذا تختار تغليف السيارات؟',
    'gallery.wrapping_advantages': 'اكتشف مزايا تغليف السيارات المهني',
    'gallery.paint_protection': 'حماية الطلاء',
    'gallery.paint_protection_desc': 'يحمي الطلاء الأصلي من الرقائق والخدوش وأضرار الأشعة فوق البنفسجية',
    'gallery.unlimited_customization': 'تخصيص غير محدود',
    'gallery.customization_desc': 'إمكانيات لونية وتصميمية لا نهائية للتخصيص الفريد',
    'gallery.reversible_process': 'عملية قابلة للعكس',
    'gallery.reversible_desc': 'يمكن إزالتها دون الإضرار بتشطيب الطلاء الأصلي',
    'gallery.professional_quality': 'جودة مهنية',
    'gallery.quality_desc': 'مواد رائدة في الصناعة وتقنيات تركيب احترافية',
    'gallery.materials_desc': 'أفلام السيارات الرائدة في الصناعة',
    'gallery.installation_desc': 'فنيون محترفون معتمدون',
    'gallery.guarantee_desc': 'ضمان على جميع الخدمات',
    'gallery.contact_quote': 'اتصل للحصول على عرض أسعار',
    'gallery.ready_transform': 'جاهز لتحويل سيارتك؟ اتصل بنا لمناقشة مشروعك والحصول على عرض أسعار مخصص.',
    'gallery.request_consultation': 'طلب استشارة',
    'gallery.professional_process': 'عمليتنا المهنية',
    'gallery.process_desc': 'من المفهوم إلى الإنجاز، نضمن نتائج استثنائية في كل خطوة',
    'gallery.consultation_design': 'الاستشارة والتصميم',
    'gallery.consultation_desc': 'نناقش رؤيتك ونقيم سيارتك وننشئ اقتراح تصميم مخصص مع توصيات المواد.',
    'gallery.preparation': 'التحضير',
    'gallery.preparation_desc': 'تنظيف شامل وتحضير سطح سيارتك لضمان الالتصاق الأمثل وجودة التشطيب.',
    'gallery.professional_installation': 'التركيب المهني',
    'gallery.installation_process_desc': 'تطبيق خبير باستخدام أدوات وتقنيات متخصصة في مرفقنا ذي البيئة المحكومة.',
    'gallery.quality_control': 'مراقبة الجودة',
    'gallery.quality_control_desc': 'فحص شامل ولمسات تشطيب لضمان النتائج المثالية ورضاك التام.',
    'gallery.premium_materials_title': 'مواد متميزة',
    'gallery.materials_subtitle': 'نستخدم فقط أفضل أفلام السيارات من الشركات المصنعة الرائدة في الصناعة',
    // Services
    'gallery.paint_protection_film': 'فيلم حماية الطلاء',
    'gallery.color_change_wrap': 'تغليف تغيير اللون', 
    'gallery.commercial_fleet': 'تغليف الأسطول التجاري',
    'gallery.specialty_finishes': 'التشطيبات المتخصصة',
    'gallery.polish_detailing': 'التلميع والتنظيف',
    'gallery.professional_detailing': 'التنظيف المهني',
    'gallery.step': 'خطوة',

    // Courses Page
    'courses.title': 'شهادة التنظيف والتلميع المهنية',
    'courses.subtitle': 'أتقن فن تنظيف السيارات باستخدام منتجات وتقنيات كوخ كيمي المهنية. احصل على شهادة من خبراء الصناعة.',
    'courses.intro_title': 'مقدمة الدورة',
    'courses.intro_subtitle': 'تعرف على ما ستحققه في هذا البرنامج التدريبي الشامل',
    'courses.course_title': 'شهادة التنظيف والتلميع المهنية',
    'courses.course_description': 'برنامج شهادة شامل لمدة 4 أيام مصمم لتعليم تقنيات تنظيف وتلميع السيارات المهنية باستخدام منتجات كوخ كيمي.',
    'courses.professional_certification': 'دورة الشهادة المهنية',
    'courses.interactive_training': 'تدريب تفاعلي وعملي لمدة 4 أيام',
    'courses.contact_pricing': 'اتصل للاستعلام عن الأسعار',
    'courses.includes_certification': 'يشمل الشهادة',
    'courses.what_learn': 'ما ستتعلمه',
    'courses.course_structure': 'هيكل الدورة لمدة 4 أيام',
    'courses.why_choose': 'لماذا تختار شهادة كوخ كيمي لدينا؟',
    'courses.course_includes': 'تشمل الدورة:',
    'courses.enroll_now': 'سجل الآن',
    'courses.contact_details': 'اتصل للتفاصيل',
    'courses.training_schedule': 'جدول التدريب',
    'courses.ready_certified': 'جاهز للحصول على الشهادة؟',
    'courses.contact_training': 'اتصل بنا لمناقشة احتياجاتك التدريبية واحجز مكانك في دورة الشهادة القادمة',
    'courses.call_us': 'اتصل بنا',
    'courses.email_us': 'راسلنا عبر البريد الإلكتروني',
    'courses.course_duration': 'مدة الدورة:',
    'courses.training_format': 'نمط التدريب:',
    'courses.class_size': 'حجم الفصل:',
    'courses.location': 'الموقع:',
    'courses.training_hours': 'ساعات التدريب:',
    'courses.next_dates': 'التواريخ القادمة المتاحة:',
    'courses.contact_schedule': 'اتصل بنا لجدولة التواريخ المفضلة لديك للتدريب. نحن نستوعب الحجوزات الفردية والجماعية مع جدولة مرنة.',
    // Learning items
    'courses.professional_techniques': 'تقنيات ومنهجيات التنظيف المهنية',
    'courses.advanced_polishing': 'طرق التلميع المتقدمة وتطبيقات المركبات',
    'courses.product_knowledge': 'معرفة منتجات كوخ كيمي والاستخدام الصحيح',
    'courses.paint_correction': 'تقنيات تصحيح واستعادة الطلاء',
    'courses.surface_assessment': 'تقييم الأسطح وتحليل العيوب',
    'courses.machine_polishing': 'إتقان التلميع الآلي (دوّار وثنائي الإجراء)',
    'courses.quality_control': 'مراقبة الجودة وتقنيات التشطيب',
    'courses.business_practices': 'ممارسات الأعمال وتميز خدمة العملاء',
    // Course structure
    'courses.day_1': 'اليوم الأول: الأساسيات',
    'courses.day_1_desc': 'معرفة منتجات كوخ كيمي وتحليل الأسطح وتقنيات التنظيف الأساسية',
    'courses.day_2': 'اليوم الثاني: التنظيف المتقدم',
    'courses.day_2_desc': 'إتقان التنظيف الداخلي/الخارجي وتطبيقات الحماية ومعايير الجودة',
    'courses.day_3': 'اليوم الثالث: إتقان التلميع',
    'courses.day_3_desc': 'تصحيح الطلاء وتقنيات المركبات وتشغيل الآلات وإزالة العيوب',
    'courses.day_4': 'اليوم الرابع: الشهادة',
    'courses.day_4_desc': 'التقييم العملي والمشاريع النهائية وشهادة كوخ كيمي الرسمية',
    // Why choose
    'courses.official_certification': 'شهادة رسمية',
    'courses.recognized_cert': 'شهادة كوخ كيمي معترف بها',
    'courses.expert_instructors': 'مدربون خبراء',
    'courses.certified_professionals': 'محترفون معتمدون من كوخ كيمي',
    'courses.interactive_hands_on': 'تفاعلي وعملي',
    'courses.practical_training': 'تدريب عملي في الواقع',
    // Course includes
    'courses.product_kit': 'مجموعة منتجات كوخ كيمي كاملة',
    'courses.equipment_access': 'الوصول لمعدات التلميع المهنية',
    'courses.training_materials': 'جميع المواد التدريبية والوثائق',
    'courses.practice_vehicles': 'مركبات تدريبية للتدريب العملي',
    'courses.certification_included': 'شهادة كوخ كيمي الرسمية',
    'courses.lunch_refreshments': 'الغداء والمرطبات طوال الأيام الأربعة',
    'courses.digital_materials': 'المواد الرقمية والموارد للدورة',
    'courses.post_support': 'الدعم والإرشاد بعد الدورة',
    // Schedule details
    'courses.four_days': '4 أيام',
    'courses.interactive_format': 'تفاعلي وعملي',
    'courses.small_groups': 'مجموعات صغيرة (أقصى 5)',
    'courses.atarot_location': 'المنطقة الصناعية عطاروت، القدس',
    'courses.tba': 'سيتم الإعلان عنها',
    'courses.course_intro_video': 'فيديو مقدمة الدورة',
    'courses.video_placeholder': 'استبدل هذا العنصر النائب بفيديو تضمينك',
    
    // About Page
    'about.badge': 'حول إم تي رابس',
    'about.title': 'صياغة التميز في العناية بالسيارات',
    'about.subtitle': 'شريك التوزيع الرسمي لكوخ كيمي يجلب منتجات العناية بالسيارات الألمانية عالية الجودة والخبرة المهنية مباشرة إليك.',
    'about.story_title': 'قصتنا',
    'about.story_p1': 'نحن فخورون بكوننا شريك التوزيع الرسمي لكوخ كيمي، نجلب منتجات العناية بالسيارات الألمانية عالية الجودة مباشرة للمحترفين والهواة في جميع أنحاء المنطقة.',
    'about.story_p2': 'مع سنوات من الخبرة العملية في التنظيف والتلميع ومعالجة الأسطح، نحن لا نبيع المنتجات فقط — نحن نعيش الحرفة. فهمنا العميق للصناعة يسمح لنا بتقديم حلول مخصصة لكل مرحلة من مراحل العناية بالمركبات.',
    'about.story_p3': 'نحن أيضاً مؤسسو إم تي رابس، أحد الأسماء الرائدة في تغليف المركبات عالي الجودة والتخصيص. عملنا يتحدث عن نفسه — الدقة والإبداع والتنفيذ المتميز في كل سيارة نلمسها.',
    'about.koch_partner': 'شريك كوخ كيمي الرسمي',
    'about.koch_desc': 'منذ عام 1968، كانت كوخ كيمي المعيار للعناية المهنية بالسيارات. كشريكهم الرسمي، نجلب لك التميز الهندسي الألماني الأصيل.',
    'about.achievements': 'الإنجازات الرئيسية',
    'about.achievement_1': 'شريك كوخ كيمي الرسمي',
    'about.achievement_1_desc': 'موزع معتمد لمنتجات العناية بالسيارات الألمانية المتميزة',
    'about.achievement_2': '+500 عميل راضٍ',
    'about.achievement_2_desc': 'خدمة المحترفين والهواة في جميع أنحاء المنطقة',
    'about.achievement_3': 'التدريب المهني',
    'about.achievement_3_desc': 'دورات شاملة في التنظيف والتلميع',
    'about.achievement_4': 'خبرة إم تي رابس',
    'about.achievement_4_desc': 'خدمات رائدة في تغليف وتخصيص المركبات',
    'about.values_title': 'قيمنا',
    'about.value_precision': 'الدقة',
    'about.value_precision_desc': 'كل تفصيل مهم في عملنا وتقديم الخدمة',
    'about.value_innovation': 'الابتكار',
    'about.value_innovation_desc': 'البقاء في المقدمة بالمنتجات والتقنيات المتطورة',
    'about.value_quality': 'الجودة',
    'about.value_quality_desc': 'فقط أجود المنتجات والمواد المهندسة ألمانياً',
    'about.value_education': 'التعليم',
    'about.value_education_desc': 'تمكين المحترفين من خلال المعرفة والتدريب',
    
    // Contact Page
    'contact.badge': 'تواصل معنا',
    'contact.title': 'اتصل بـ MT Wraps',
    'contact.subtitle': 'جاهز لرفع مستوى العناية بمركبتك؟ تواصل مع فريقنا للمنتجات والتدريب أو خدمات التغليف المهنية.',
    'contact.form_title': 'أرسل لنا رسالة',
    'contact.form_subtitle': 'املأ النموذج أدناه وسنعاود الاتصال بك خلال 24 ساعة',
    'contact.name': 'الاسم الكامل',
    'contact.name_placeholder': 'أدخل اسمك الكامل',
    'contact.email': 'عنوان البريد الإلكتروني',
    'contact.email_placeholder': 'أدخل عنوان بريدك الإلكتروني',
    'contact.phone': 'رقم الهاتف',
    'contact.phone_placeholder': 'أدخل رقم هاتفك',
    'contact.company': 'الشركة',
    'contact.company_placeholder': 'أدخل اسم شركتك',
    'contact.service_interest': 'الاهتمام بالخدمة',
    'contact.service_interest_placeholder': 'اختر خدمة',
    'contact.subject': 'الموضوع',
    'contact.subject_placeholder': 'موضوع موجز لاستفسارك',
    'contact.message': 'الرسالة',
    'contact.message_placeholder': 'أخبرنا عن احتياجاتك...',
    'contact.send_message': 'إرسال الرسالة',
    'contact.sending': 'جاري الإرسال...',
    'contact.info_title': 'معلومات الاتصال',
    'contact.phone_title': 'الهاتف',
    'contact.phone_desc': 'اتصل بنا خلال ساعات العمل',
    'contact.email_title': 'البريد الإلكتروني',
    'contact.email_desc': 'نرد خلال 24 ساعة',
    'contact.location_title': 'الموقع',
    'contact.location_desc': 'قم بزيارة صالة العرض وورشة العمل',
    'contact.hours_title': 'ساعات العمل',
    'contact.hours_desc': 'الأحد إلى الخميس، اتصل للأوقات المحددة',
    'contact.success_title': 'تم إرسال الرسالة بنجاح!',
    'contact.success_desc': 'سنعاود الاتصال بك خلال 24 ساعة.',
    'contact.error_title': 'خطأ',
    'contact.error_desc': 'فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    
    // Products Page
    'products.all_categories': 'جميع الفئات',
    'products.view_details': 'عرض التفاصيل',
    'products.add_to_cart': 'أضف إلى السلة',
    'products.in_stock': 'متوفر',
    'products.out_of_stock': 'غير متوفر',
    'products.price_tba': 'سيُعلن لاحقاً',
    'products.price_coming_soon': 'السعر قريباً',
    'products.lowest_price': 'من',
    'products.select_variant': 'اختر المتغير',
    'products.back_to_products': 'العودة إلى المنتجات',
    
    // Footer
    'footer.company_name': 'MTKcx',
    'footer.company_desc': 'الموزع الرسمي لكوخ كيمي يقدم منتجات العناية المتميزة بالسيارات والتدريب المهني وخدمات التغليف المتخصصة.',
    'footer.quick_links': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.service_1': 'العناية المهنية بالسيارات',
    'footer.service_2': 'تدريب التنظيف',
    'footer.service_3': 'تغليف السيارات',
    'footer.service_4': 'توزيع المنتجات',
    'footer.copyright': '© 2025 MT Wraps. جميع الحقوق محفوظة. | كوخ كيمي',
    
    // Stats
    'stats.products': 'منتج متميز',
    'stats.customers': 'عميل سعيد',
    'stats.experience': 'سنوات خبرة',

    // Products
    'products.title': 'كتالوج منتجات كوخ كيمي',
    'products.subtitle': 'اكتشف مجموعتنا الكاملة من منتجات تفصيل السيارات المهنية. كل منتج متوفر بأحجام متعددة لتلبية احتياجاتك المحددة.',
    'products.search_placeholder': 'البحث في المنتجات بالاسم أو الوصف أو رمز المنتج...',
    'products.filters': 'المرشحات',
    'products.showing_results': 'عرض {count} من {total} منتج',
    'products.clear_filters': 'مسح المرشحات',
    'products.clear_all_filters': 'مسح جميع المرشحات',
    'products.no_products': 'لم يتم العثور على منتجات تتطابق مع معاييرك.',
    'products.loading': 'جاري التحميل...',

    // Common
    'common.learn_more': 'اعرف أكثر',
    'common.contact_us': 'اتصل بنا',
    'common.get_started': 'ابدأ الآن',
    'common.search': 'بحث',
    'common.professional_training': 'التدريب المهني',
    'common.mt_wraps_services': 'خدمات إم تي رابس',
    'common.official_partner': 'الشريك الرسمي لكوخ كيمي',
    'common.loading': 'جاري التحميل...',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تحرير',
    'common.delete': 'حذف',
    'common.close': 'إغلاق',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.view_all': 'عرض الكل',
    'common.show_more': 'عرض المزيد',
    'common.show_less': 'عرض أقل',
    'common.read_more': 'اقرأ المزيد',
    'common.visit_us': 'زورنا',
    'common.enrollment_interest': 'تم استلام اهتمام التسجيل!',
    'common.contact_course_info': 'سنتواصل معك حول شهادة كوخ كيمي المهنية للتنظيف والتلميع خلال 24 ساعة.',
    'common.get_course_info': 'احصل على معلومات الدورة',
    'common.koch_official_training': 'التدريب الرسمي لكوخ كيمي',
    'common.only_official_course': 'هذه هي دورة الشهادة الرسمية الوحيدة لكوخ كيمي في المنطقة. عند الانتهاء، ستصبح منظف كوخ كيمي مهني معتمد.',
    'common.quote_request_received': 'تم استلام طلب العرض!',
    'common.contact_service_hours': 'سنتواصل معك حول {service} خلال 24 ساعة.',
    'common.beyond_products': 'أبعد من المنتجات - التعليم والتميز',
    'common.why_choose_mt': 'لماذا تختار إم تي رابس؟',
    'common.professional_training_programs': 'برامج التدريب المهني',
    'common.expert_wrapping_services': 'خدمات التغليف المتخصصة',
    'common.fast_response_time': 'وقت استجابة سريع',
    'common.our_work_gallery': 'معرض أعمالنا',
    'common.explore_portfolio': 'استكشف مجموعة أعمالنا لتحويلات السيارات والمشاريع المخصصة',
    'common.project_gallery_image': 'صورة معرض المشروع',
    'common.images_coming_soon': '(الصور قادمة قريباً)',
    'common.view_full_gallery': 'عرض المعرض الكامل',
    'common.ready_transform_vehicle': 'جاهز لتحويل سيارتك؟',
    'common.contact_consultation': 'اتصل بنا اليوم للحصول على استشارة شخصية وعرض أسعار لمشروع تغليف سيارتك.',
    'common.call_for_quote': 'اتصل للحصول على عرض أسعار',
    'common.schedule_consultation': 'حدد موعد استشارة',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.products': 'מוצרים',
    'nav.courses': 'קורסים',
    'nav.wrapping': 'עיטוף רכבים',
    'nav.about': 'אודות',
    'nav.contact': 'צור קשר',
    
    // Hero Section
    'hero.title': 'פתרונות טיפוח רכב והכשרה מתקדמים',
    'hero.subtitle': 'מפיץ רשמי של Koch-Chemie המציע מוצרי ניקיון מקצועיים, קורסי הכשרה מומחים ושירותי עיטוף רכבים מתקדמים.',
    'hero.cta.products': 'קנה מוצרים',
    'hero.cta.courses': 'צפה בקורסים',
    
    // Services Section
    'services.title': 'השירותים שלנו',
    'services.subtitle': 'פתרונות טיפוח רכב מקיפים מתוצרים להכשרה ושירותי עיטוף מתקדמים',
    'services.koch_title': 'מוצרי Koch-Chemie',
    'services.koch_description': 'מוצרי טיפוח רכב מקצועיים מהיצרן המוביל בגרמניה.',
    'services.koch_features.1': 'טיפוח רכב מתקדם',
    'services.koch_features.2': 'ניקיון מקצועי',
    'services.koch_features.3': 'איכות מובילה בתעשייה',
    'services.koch_cta': 'צפה במוצרים',
    'services.courses_title': 'קורסי ניקיון',
    'services.courses_description': 'תוכניות הכשרה מקצועיות לטכניקות ניקיון והברקת רכבים מקצועיים.',
    'services.courses_features.1': 'הכשרה מעשית',
    'services.courses_features.2': 'באינטרנט ובאופן אישי',
    'services.courses_features.3': 'כולל הסמכה',
    'services.courses_cta': 'הירשם היום',
    'services.wrapping_title': 'שירותי MT Wraps',
    'services.wrapping_description': 'שירותי עיטוף רכבים מתקדמים והתקנת ויניל למראה מדהים.',
    'services.wrapping_features.1': 'עיצובים מותאמים אישית',
    'services.wrapping_features.2': 'חומרים מתקדמים',
    'services.wrapping_features.3': 'התקנה מקצועית',
    'services.wrapping_cta': 'צפה בגלריה',

    // Gallery/Wrapping Page
    'gallery.title': 'עיטוף רכבים מקצועי',
    'gallery.subtitle': 'שנה את הרכב שלך עם סרטי רכב מתקדמים. משינויי צבע מלאים לפתרונות הגנה, אנו מספקים תוצאות יוצאות דופן עם חומרים מובילים בתעשייה.',
    'gallery.services_title': 'שירותי העיטוף שלנו',
    'gallery.services_subtitle': 'צור איתנו קשר לדיון על הצרכים שלך ממגוון שירותי עיטוף רכבים וניקיון מקצועיים',
    'gallery.professional_title': 'שירותי רכב מקצועיים',
    'gallery.professional_description': 'אנו מציעים מגוון מקיף של שירותי עיטוף רכבים וניקיון. צור איתנו קשר לדיון על השירות המתאים ביותר לצרכים ולתקציב שלך.',
    'gallery.wrapping_services': 'שירותי עיטוף',
    'gallery.additional_services': 'שירותים נוספים',
    'gallery.why_choose': 'למה לבחור בשירותים שלנו?',
    'gallery.premium_materials': 'חומרים מתקדמים',
    'gallery.premium_materials_desc': 'סרטי רכב מובילים בתעשייה',
    'gallery.expert_installation': 'התקנה מקצועית',
    'gallery.expert_installation_desc': 'טכנאים מקצועיים מוסמכים',
    'gallery.quality_guarantee': 'ערבות איכות',
    'gallery.quality_guarantee_desc': 'ערבות על כל השירותים',
    'gallery.why_choose_wrapping': 'למה לבחור בעיטוף רכבים?',
    'gallery.wrapping_advantages': 'גלה את היתרונות של עיטוף רכבים מקצועי',
    'gallery.paint_protection': 'הגנת צבע',
    'gallery.paint_protection_desc': 'מגן על הצבע המקורי מפגיעות, שריטות ונזקי UV',
    'gallery.unlimited_customization': 'התאמה אישית בלתי מוגבלת',
    'gallery.customization_desc': 'אפשרויות צבע ועיצוב אינסופיות להתאמה אישית ייחודית',
    'gallery.reversible_process': 'תהליך הפיך',
    'gallery.reversible_desc': 'ניתן להסרה ללא פגיעה בגימור הצבע המקורי',
    'gallery.professional_quality': 'איכות מקצועית',
    'gallery.quality_desc': 'חומרים מובילים בתעשייה וטכניקות התקנה מומחיות',
    'gallery.materials_desc': 'סרטי רכב מובילים בתעשייה',
    'gallery.installation_desc': 'טכנאים מקצועיים מוסמכים',
    'gallery.guarantee_desc': 'ערבות על כל השירותים',
    'gallery.contact_quote': 'צור קשר להצעת מחיר',
    'gallery.ready_transform': 'מוכן לשנות את הרכב שלך? צור איתנו קשר לדיון על הפרויקט שלך ולקבלת הצעת מחיר מותאמת אישית.',
    'gallery.request_consultation': 'בקש ייעוץ',
    'gallery.professional_process': 'התהליך המקצועי שלנו',
    'gallery.process_desc': 'מהרעיון להשלמה, אנו מבטיחים תוצאות יוצאות דופן בכל שלב',
    'gallery.consultation_design': 'ייעוץ ועיצוב',
    'gallery.consultation_desc': 'אנחנו דנים בחזון שלך, מעריכים את הרכב שלך ויוצרים הצעת עיצוב מותאמת עם המלצות חומרים.',
    'gallery.preparation': 'הכנה',
    'gallery.preparation_desc': 'ניקיון יסודי והכנת משטח הרכב שלך להבטחת הידבקות מיטבית ואיכות גימור.',
    'gallery.professional_installation': 'התקנה מקצועית',
    'gallery.installation_process_desc': 'יישום מומחה באמצעות כלים וטכניקות מיוחדות במתקן הסביבה המבוקרת שלנו.',
    'gallery.quality_control': 'בקרת איכות',
    'gallery.quality_control_desc': 'בדיקה מקיפה ומגע גימור להבטחת תוצאות מושלמות ושביעות רצונך המלאה.',
    'gallery.premium_materials_title': 'חומרים מעולים',
    'gallery.materials_subtitle': 'אנחנו משתמשים רק בסרטי הרכב המשובחים ביותר מהיצרנים המובילים בתעשייה',
    // Services
    'gallery.paint_protection_film': 'סרט הגנת צבע',
    'gallery.color_change_wrap': 'עיטוף שינוי צבע', 
    'gallery.commercial_fleet': 'עיטוף צי מסחרי',
    'gallery.specialty_finishes': 'גימורים מיוחדים',
    'gallery.polish_detailing': 'הברקה וניקיון',
    'gallery.professional_detailing': 'ניקיון מקצועי',
    'gallery.step': 'שלב',

    // Courses Page
    'courses.title': 'הסמכת ניקיון והברקה מקצועית',
    'courses.subtitle': 'השלט באמנות ניקיון הרכב עם מוצרים וטכניקות מקצועיות של Koch Chemie. קבל הסמכה ממומחי התעשייה.',
    'courses.intro_title': 'מבוא לקורס',
    'courses.intro_subtitle': 'למד מה תשיג בתוכנית ההכשרה המקיפה הזו',
    'courses.course_title': 'הסמכת ניקיון והברקה מקצועית',
    'courses.course_description': 'תוכנית הסמכה מקיפה של 4 ימים שנועדה ללמד טכניקות ניקיון והברקת רכבים מקצועיות באמצעות מוצרי Koch Chemie.',
    'courses.professional_certification': 'קורס הסמכה מקצועית',
    'courses.interactive_training': 'הכשרה אינטראקטיבית ומעשית למשך 4 ימים',
    'courses.contact_pricing': 'צור קשר לתמחור',
    'courses.includes_certification': 'כולל הסמכה',
    'courses.what_learn': 'מה תלמדו',
    'courses.course_structure': 'מבנה הקורס למשך 4 ימים',
    'courses.why_choose': 'למה לבחור בהסמכת Koch Chemie שלנו?',
    'courses.course_includes': 'הקורס כולל:',
    'courses.enroll_now': 'הירשם עכשיו',
    'courses.contact_details': 'צור קשר לפרטים',
    'courses.training_schedule': 'לוח זמנים להכשרה',
    'courses.ready_certified': 'מוכן לקבל הסמכה?',
    'courses.contact_training': 'צור איתנו קשר לדיון על צרכי ההכשרה שלך ושמור את מקומך בקורס ההסמכה הבא שלנו',
    'courses.call_us': 'התקשר אלינו',
    'courses.email_us': 'שלח לנו מייל',
    'courses.course_duration': 'משך הקורס:',
    'courses.training_format': 'פורמט ההכשרה:',
    'courses.class_size': 'גודל הכיתה:',
    'courses.location': 'מיקום:',
    'courses.training_hours': 'שעות הכשרה:',
    'courses.next_dates': 'התאריכים הזמינים הבאים:',
    'courses.contact_schedule': 'צור איתנו קשר לתזמן את תאריכי ההכשרה המועדפים עליך. אנחנו מתאימים הזמנות אישיות וקבוצתיות עם תזמון גמיש.',
    // Learning items
    'courses.professional_techniques': 'טכניקות ומתודולוגיות ניקיון מקצועיות',
    'courses.advanced_polishing': 'שיטות הברקה מתקדמות ויישומי תרכובות',
    'courses.product_knowledge': 'ידע על מוצרי Koch Chemie ושימוש נכון',
    'courses.paint_correction': 'טכניקות תיקון ושחזור צבע',
    'courses.surface_assessment': 'הערכת משטחים וניתוח פגמים',
    'courses.machine_polishing': 'שליטה בהברקה מכנית (סיבובית וכפולת פעולה)',
    'courses.quality_control': 'בקרת איכות וטכניקות גימור',
    'courses.business_practices': 'שיטות עסקיות ומצוינות בשירות לקוחות',
    // Course structure
    'courses.day_1': 'יום 1: יסודות',
    'courses.day_1_desc': 'ידע על מוצרי Koch Chemie, ניתוח משטחים וטכניקות ניקיון בסיסיות',
    'courses.day_2': 'יום 2: ניקיון מתקדם',
    'courses.day_2_desc': 'שליטה בניקיון פנימי/חיצוני, יישומי הגנה ותקני איכות',
    'courses.day_3': 'יום 3: שליטה בהברקה',
    'courses.day_3_desc': 'תיקון צבע, טכניקות תרכובות, הפעלת מכונות והסרת פגמים',
    'courses.day_4': 'יום 4: הסמכה',
    'courses.day_4_desc': 'הערכה מעשית, פרויקטים סופיים והסמכת Koch Chemie רשמית',
    // Why choose
    'courses.official_certification': 'הסמכה רשמית',
    'courses.recognized_cert': 'הסמכת Koch Chemie מוכרת',
    'courses.expert_instructors': 'מדריכים מומחים',
    'courses.certified_professionals': 'מקצועיים מוסמכים של Koch Chemie',
    'courses.interactive_hands_on': 'אינטראקטיבי ומעשי',
    'courses.practical_training': 'הכשרה מעשית בעולם האמיתי',
    // Course includes
    'courses.product_kit': 'ערכת מוצרי Koch Chemie מלאה',
    'courses.equipment_access': 'גישה לציוד הברקה מקצועי',
    'courses.training_materials': 'כל החומרים והתיעוד להכשרה',
    'courses.practice_vehicles': 'רכבי תרגול להכשרה מעשית',
    'courses.certification_included': 'הסמכת Koch Chemie רשמית',
    'courses.lunch_refreshments': 'ארוחת צהריים ומשקאות כל 4 הימים',
    'courses.digital_materials': 'חומרים דיגיטליים ומשאבים לקורס',
    'courses.post_support': 'תמיכה והדרכה לאחר הקורס',
    // Schedule details
    'courses.four_days': '4 ימים',
    'courses.interactive_format': 'אינטראקטיבי ומעשי',
    'courses.small_groups': 'קבוצות קטנות (מקסימום 5)',
    'courses.atarot_location': 'האזור התעשייתי עטרות, ירושלים',
    'courses.tba': 'יוכרז',
    'courses.course_intro_video': 'סרטון מבוא לקורס',
    'courses.video_placeholder': 'החלף את המקום השמור הזה עם הסרטון שלך',
    
    // About Page
    'about.badge': 'אודות MT Wraps',
    'about.title': 'יצירת מעולות בטיפוח רכב',
    'about.subtitle': 'שותף הפצה רשמי של Koch-Chemie המביא מוצרי טיפוח רכב גרמניים ברמה עולמית ומומחיות מקצועית ישירות אליכם.',
    'about.story_title': 'הסיפור שלנו',
    'about.story_p1': 'אנחנו גאים להיות שותפי הפצה רשמיים של Koch-Chemie, המביאים מוצרי טיפוח רכב גרמניים ברמה עולמית ישירות למקצועיים וחובבים ברחבי האזור.',
    'about.story_p2': 'עם שנים של ניסיון מעשי בניקיון, הברקה וטיפול במשטחים, אנחנו לא רק מוכרים מוצרים — אנחנו חיים את המקצוע. ההבנה העמוקה שלנו בתעשייה מאפשרת לנו לספק פתרונות מותאמים לכל שלב של טיפוח הרכב.',
    'about.story_p3': 'אנחנו גם מייסדי MT Wraps, אחד מהשמות המובילים בעיטוף רכבים איכותי והתאמה אישית. העבודה שלנו מדברת בעד עצמה — דיוק, יצירתיות וביצוע מעולה בכל רכב שאנחנו נוגעים בו.',
    'about.koch_partner': 'שותף רשמי של Koch-Chemie',
    'about.koch_desc': 'מאז 1968, Koch-Chemie הייתה הסטנדרט לטיפוח רכב מקצועי. כשותפיהם הרשמיים, אנחנו מביאים לכם מצוינות הנדסית גרמנית אותנטית.',
    'about.achievements': 'הישגים עיקריים',
    'about.achievement_1': 'שותף רשמי של Koch-Chemie',
    'about.achievement_1_desc': 'מפיץ מורשה של מוצרי טיפוח רכב גרמניים מעולים',
    'about.achievement_2': '+500 לקוחות מרוצים',
    'about.achievement_2_desc': 'משרתים מקצועיים וחובבים ברחבי האזור',
    'about.achievement_3': 'הכשרה מקצועית',
    'about.achievement_3_desc': 'קורסים מקיפים בניקיון והברקה',
    'about.achievement_4': 'מומחיות MT Wraps',
    'about.achievement_4_desc': 'שירותי עיטוף והתאמה אישית מובילים',
    'about.values_title': 'הערכים שלנו',
    'about.value_precision': 'דיוק',
    'about.value_precision_desc': 'כל פרט חשוב בעבודתנו ובמתן השירות',
    'about.value_innovation': 'חדשנות',
    'about.value_innovation_desc': 'להישאר בחזית עם מוצרים וטכניקות מתקדמות',
    'about.value_quality': 'איכות',
    'about.value_quality_desc': 'רק המוצרים והחומרים הגרמניים המעולים ביותר',
    'about.value_education': 'חינוך',
    'about.value_education_desc': 'העצמת מקצועיים באמצעות ידע והכשרה',
    
    // Contact Page
    'contact.badge': 'צור קשר',
    'contact.title': 'צור קשר עם MT Wraps',
    'contact.subtitle': 'מוכן להעלות את רמת הטיפוח ברכב שלך? צור קשר עם הצוות שלנו למוצרים, הכשרה או שירותי עיטוף מקצועיים.',
    'contact.form_title': 'שלח לנו הודעה',
    'contact.form_subtitle': 'מלא את הטופס למטה ונחזור אליך תוך 24 שעות',
    'contact.name': 'שם מלא',
    'contact.name_placeholder': 'הכנס את שמך המלא',
    'contact.email': 'כתובת אימייל',
    'contact.email_placeholder': 'הכנס את כתובת האימייל שלך',
    'contact.phone': 'מספר טלפון',
    'contact.phone_placeholder': 'הכנס את מספר הטלפון שלך',
    'contact.company': 'חברה',
    'contact.company_placeholder': 'הכנס את שם החברה שלך',
    'contact.service_interest': 'עניין בשירות',
    'contact.service_interest_placeholder': 'בחר שירות',
    'contact.subject': 'נושא',
    'contact.subject_placeholder': 'נושא קצר של הפנייה שלך',
    'contact.message': 'הודעה',
    'contact.message_placeholder': 'ספר לנו על הצרכים שלך...',
    'contact.send_message': 'שלח הודעה',
    'contact.sending': 'שולח...',
    'contact.info_title': 'פרטי קשר',
    'contact.phone_title': 'טלפון',
    'contact.phone_desc': 'התקשר אלינו בשעות העבודה',
    'contact.email_title': 'אימייל',
    'contact.email_desc': 'אנחנו מגיבים תוך 24 שעות',
    'contact.location_title': 'מיקום',
    'contact.location_desc': 'בקר בחדר התצוגה ובמוסך שלנו',
    'contact.hours_title': 'שעות עבודה',
    'contact.hours_desc': 'ראשון עד חמישי, צור קשר לשעות ספציפיות',
    'contact.success_title': 'ההודעה נשלחה בהצלחה!',
    'contact.success_desc': 'נחזור אליך תוך 24 שעות.',
    'contact.error_title': 'שגיאה',
    'contact.error_desc': 'שליחת ההודעה נכשלה. אנא נסה שוב.',
    
    // Products Page
    'products.all_categories': 'כל הקטגוריות',
    'products.view_details': 'צפה בפרטים',
    'products.add_to_cart': 'הוסף לעגלה',
    'products.in_stock': 'במלאי',
    'products.out_of_stock': 'לא במלאי',
    'products.price_tba': 'TBA',
    'products.price_coming_soon': 'מחיר בקרוב',
    'products.lowest_price': 'החל מ',
    'products.select_variant': 'בחר וריאנט',
    'products.back_to_products': 'חזור למוצרים',
    
    // Footer
    'footer.company_name': 'MTKcx',
    'footer.company_desc': 'מפיץ רשמי של Koch-Chemie המספק מוצרי טיפוח רכב מעולים, הכשרה מקצועית ושירותי עיטוף מומחים.',
    'footer.quick_links': 'קישורים מהירים',
    'footer.services': 'שירותים',
    'footer.service_1': 'טיפוח רכב מקצועי',
    'footer.service_2': 'הכשרת ניקיון',
    'footer.service_3': 'עיטוף רכבים',
    'footer.service_4': 'הפצת מוצרים',
    'footer.copyright': '© 2025 MT Wraps. כל הזכויות שמורות. | Koch-Chemie',
    
    // Stats
    'stats.products': 'מוצרים מעולים',
    'stats.customers': 'לקוחות מרוצים',
    'stats.experience': 'שנות ניסיון',

    // Products
    'products.title': 'קטלוג מוצרי קוך כימי',
    'products.subtitle': 'גלה את המגוון השלם שלנו של מוצרי פירוט רכב מקצועיים. כל מוצר זמין בגדלים מרובים לענות על הצרכים הספציפיים שלך.',
    'products.search_placeholder': 'חפש מוצרים לפי שם, תיאור או קוד מוצר...',
    'products.filters': 'מסננים',
    'products.showing_results': 'מציג {count} מתוך {total} מוצרים',
    'products.clear_filters': 'נקה מסננים',
    'products.clear_all_filters': 'נקה את כל המסננים',
    'products.no_products': 'לא נמצאו מוצרים התואמים לקריטריונים שלך.',
    'products.loading': 'טוען...',

    // Common
    'common.learn_more': 'למד עוד',
    'common.contact_us': 'צור קשר',
    'common.get_started': 'התחל',
    'common.search': 'חיפוש',
    'common.professional_training': 'הכשרה מקצועית',
    'common.mt_wraps_services': 'שירותי MT Wraps',
    'common.official_partner': 'שותף רשמי של Koch-Chemie',
    'common.loading': 'טוען...',
    'common.submit': 'שלח',
    'common.cancel': 'בטל',
    'common.save': 'שמור',
    'common.edit': 'ערוך',
    'common.delete': 'מחק',
    'common.close': 'סגור',
    'common.next': 'הבא',
    'common.previous': 'הקודם',
    'common.view_all': 'צפה בהכל',
    'common.show_more': 'הצג עוד',
    'common.show_less': 'הצג פחות',
    'common.read_more': 'קרא עוד',
    'common.visit_us': 'בקר אותנו',
    'common.enrollment_interest': 'עניין ברישום התקבל!',
    'common.contact_course_info': 'ניצור איתך קשר לגבי הסמכת Koch Chemie המקצועית לניקיון והברקה תוך 24 שעות.',
    'common.get_course_info': 'קבל מידע על הקורס',
    'common.koch_official_training': 'הכשרה רשמית של Koch Chemie',
    'common.only_official_course': 'זהו קורס ההסמכה הרשמי היחיד של Koch Chemie באזור. עם השלמתו, תהיה מנקה מקצועי מוסמך של Koch Chemie.',
    'common.quote_request_received': 'בקשת הצעת מחיר התקבלה!',
    'common.contact_service_hours': 'ניצור איתך קשר לגבי {service} תוך 24 שעות.',
    'common.beyond_products': 'מעבר למוצרים - חינוך ומצוינות',
    'common.why_choose_mt': 'למה לבחור ב-MT Wraps?',
    'common.professional_training_programs': 'תוכניות הכשרה מקצועיות',
    'common.expert_wrapping_services': 'שירותי עיטוף מומחים',
    'common.fast_response_time': 'זמן תגובה מהיר',
    'common.our_work_gallery': 'גלריית העבודות שלנו',
    'common.explore_portfolio': 'חקור את תיק העבודות שלנו של שינויי רכבים ופרויקטים מותאמים אישית',
    'common.project_gallery_image': 'תמונת גלריית פרויקט',
    'common.images_coming_soon': '(תמונות בקרוב)',
    'common.view_full_gallery': 'צפה בגלריה המלאה',
    'common.ready_transform_vehicle': 'מוכן לשנות את הרכב שלך?',
    'common.contact_consultation': 'צור איתנו קשר היום לייעוץ אישי והצעת מחיר לפרויקט עיטוף הרכב שלך.',
    'common.call_for_quote': 'התקשר להצעת מחיר',
    'common.schedule_consultation': 'תזמן ייעוץ',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    document.dir = lang === 'ar' || lang === 'he' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations[typeof currentLanguage]] || key;
  };

  const isRTL = currentLanguage === 'ar' || currentLanguage === 'he';

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};