import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'he';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.courses': 'Courses',
    'nav.wrapping': 'Car Wrapping',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Premium Car Care & Training Solutions',
    'hero.subtitle': 'Official Koch-Chemie distributor offering professional detailing products, expert training courses, and premium car wrapping services.',
    'hero.cta.products': 'Shop Products',
    'hero.cta.courses': 'View Courses',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive Car Care solutions from products to training to premium wrapping services',
    'services.koch_title': 'Koch-Chemie Products',
    'services.koch_description': 'Professional-grade car care products from Germany\'s leading manufacturer.',
    'services.koch_features.1': 'Premium car care',
    'services.koch_features.2': 'Professional detailing',
    'services.koch_features.3': 'Industry-leading quality',
    'services.koch_cta': 'View Products',
    'services.courses_title': 'Detailing Courses',
    'services.courses_description': 'Expert training programs for professional car detailing and polishing techniques.',
    'services.courses_features.1': 'Hands-on training',
    'services.courses_features.2': 'Online & in-person',
    'services.courses_features.3': 'Certification included',
    'services.courses_cta': 'Enroll Today',
    'services.wrapping_title': 'MT Wraps Services',
    'services.wrapping_description': 'Premium car wrapping and vinyl installation services for a stunning finish.',
    'services.wrapping_features.1': 'Custom designs',
    'services.wrapping_features.2': 'Premium materials',
    'services.wrapping_features.3': 'Expert installation',
    'services.wrapping_cta': 'View Gallery',

    // Gallery/Wrapping Page
    'gallery.title': 'Professional Vehicle Wrapping',
    'gallery.subtitle': 'Transform your vehicle with premium automotive films. From complete color changes to protective solutions, we deliver exceptional results with industry-leading materials.',
    'gallery.services_title': 'Our Wrapping Services',
    'gallery.services_subtitle': 'Contact us to discuss your needs from our variety of professional vehicle wrapping and detailing services',
    'gallery.professional_title': 'Professional Vehicle Services',
    'gallery.professional_description': 'We offer a comprehensive range of vehicle wrapping and detailing services. Contact us to discuss which service best fits your needs and budget.',
    'gallery.wrapping_services': 'Wrapping Services',
    'gallery.additional_services': 'Additional Services',
    'gallery.why_choose': 'Why Choose Our Services?',
    'gallery.premium_materials': 'Premium Materials',
    'gallery.premium_materials_desc': 'Industry-leading automotive films',
    'gallery.expert_installation': 'Expert Installation',
    'gallery.expert_installation_desc': 'Professional certified technicians',
    'gallery.quality_guarantee': 'Quality Guarantee',
    'gallery.quality_guarantee_desc': 'Warranty on all services',
    'gallery.contact_quote': 'Ready to transform your vehicle? Contact us to discuss your project and get a personalized quote.',
    'gallery.contact_for_quote': 'Contact for Quote',
    'gallery.request_consultation': 'Request Consultation',

    // About Page
    'about.badge': 'About MT Wraps',
    'about.title': 'Crafting Excellence in Automotive Care',
    'about.subtitle': 'Official Koch-Chemie distribution partner bringing world-class German car care products and professional expertise directly to you.',
    'about.story_title': 'Our Story',
    'about.story_p1': 'We are proud to be an official Koch-Chemie distribution partner, bringing world-class German car care products directly to professionals and enthusiasts across the region.',
    'about.story_p2': 'With years of hands-on experience in detailing, polishing, and surface treatment, we don\'t just sell products — we live the craft. Our deep understanding of the industry allows us to provide tailored solutions for every stage of vehicle care, from pre-wash to final finish.',
    'about.story_p3': 'We are also the founders of MT Wraps, one of the leading names in high-quality vehicle wrapping and customization. Our work speaks for itself — precision, creativity, and premium execution on every car we touch.',
    'about.koch_partner': 'Koch-Chemie Official Partner',
    'about.koch_desc': 'Since 1968, Koch-Chemie has been the benchmark for professional car care. As their official partner, we bring you authentic German engineering excellence.',
    'about.achievements': 'Key Achievements',
    'about.achievement_1': 'Official Koch-Chemie Partner',
    'about.achievement_1_desc': 'Authorized distributor of premium German car care products',
    'about.achievement_2': '500+ Satisfied Clients',
    'about.achievement_2_desc': 'Serving professionals and enthusiasts across the region',
    'about.achievement_3': 'Professional Training',
    'about.achievement_3_desc': 'Comprehensive detailing and polishing courses',
    'about.achievement_4': 'MT Wraps Expertise',
    'about.achievement_4_desc': 'Leading vehicle wrapping and customization services',
    'about.values_title': 'Our Values',
    'about.value_precision': 'Precision',
    'about.value_precision_desc': 'Every detail matters in our work and service delivery',
    'about.value_innovation': 'Innovation',
    'about.value_innovation_desc': 'Staying ahead with cutting-edge products and techniques',
    'about.value_quality': 'Quality',
    'about.value_quality_desc': 'Only the finest German-engineered products and materials',
    'about.value_education': 'Education',
    'about.value_education_desc': 'Empowering professionals through knowledge and training',
    
    // Contact Page
    'contact.badge': 'Get In Touch',
    'contact.title': 'Contact MT Wraps',
    'contact.subtitle': 'Ready to elevate your vehicle care? Get in touch with our team for products, training, or professional wrapping services.',
    'contact.form_title': 'Send us a Message',
    'contact.form_subtitle': 'Fill out the form below and we\'ll get back to you within 24 hours',
    'contact.name': 'Full Name',
    'contact.name_placeholder': 'Enter your full name',
    'contact.email': 'Email Address',
    'contact.email_placeholder': 'Enter your email address',
    'contact.phone': 'Phone Number',
    'contact.phone_placeholder': 'Enter your phone number',
    'contact.company': 'Company',
    'contact.company_placeholder': 'Enter your company name',
    'contact.service_interest': 'Service Interest',
    'contact.service_interest_placeholder': 'Select a service',
    'contact.subject': 'Subject',
    'contact.subject_placeholder': 'Brief subject of your inquiry',
    'contact.message': 'Message',
    'contact.message_placeholder': 'Tell us about your needs...',
    'contact.send_message': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.info_title': 'Contact Information',
    'contact.phone_title': 'Phone',
    'contact.phone_desc': 'Call us during business hours',
    'contact.email_title': 'Email',
    'contact.email_desc': 'We respond within 24 hours',
    'contact.location_title': 'Location',
    'contact.location_desc': 'Visit our showroom and workshop',
    'contact.hours_title': 'Business Hours',
    'contact.hours_desc': 'Sunday to Thursday, contact for specific times',
    'contact.success_title': 'Message Sent Successfully!',
    'contact.success_desc': 'We\'ll get back to you within 24 hours.',
    'contact.error_title': 'Error',
    'contact.error_desc': 'Failed to send message. Please try again.',
    
    // Products Page
    'products.search_placeholder': 'Search products...',
    'products.all_categories': 'All Categories',
    'products.no_products': 'No products found matching your criteria.',
    'products.view_details': 'View Details',
    'products.add_to_cart': 'Add to Cart',
    'products.in_stock': 'In Stock',
    'products.out_of_stock': 'Out of Stock',
    'products.price_tba': 'TBA',
    'products.price_coming_soon': 'Price Coming Soon',
    'products.lowest_price': 'From',
    'products.select_variant': 'Select Variant',
    'products.back_to_products': 'Back to Products',
    
    // Footer
    'footer.company_name': 'MTKcx',
    'footer.company_desc': 'Official Koch-Chemie distributor providing premium car care products, professional training, and expert wrapping services.',
    'footer.quick_links': 'Quick Links',
    'footer.services': 'Services',
    'footer.service_1': 'Professional Car Care',
    'footer.service_2': 'Detailing Training',
    'footer.service_3': 'Car Wrapping',
    'footer.service_4': 'Product Distribution',
    'footer.copyright': '© 2025 MT Wraps. All rights reserved. | Koch-Chemie',
    
    // Stats
    'stats.products': 'Premium Products',
    'stats.customers': 'Happy Customers',
    'stats.experience': 'Years Experience',

    // Common
    'common.learn_more': 'Learn More',
    'common.contact_us': 'Contact Us',
    'common.get_started': 'Get Started',
    'common.search': 'Search',
    'common.professional_training': 'Professional Training',
    'common.mt_wraps_services': 'MT Wraps Services',
    'common.official_partner': 'Official Koch-Chemie Partner',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.view_all': 'View All',
    'common.show_more': 'Show More',
    'common.show_less': 'Show Less',
    'common.read_more': 'Read More',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.courses': 'الدورات',
    'nav.wrapping': 'تغليف السيارات',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    
    // Hero Section
    'hero.title': 'حلول العناية بالسيارات والتدريب المتميزة',
    'hero.subtitle': 'الموزع الرسمي لكوخ كيمي يقدم منتجات التنظيف المهنية ودورات التدريب المتخصصة وخدمات تغليف السيارات المتميزة.',
    'hero.cta.products': 'تسوق المنتجات',
    'hero.cta.courses': 'عرض الدورات',
    
    // Services Section
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول شاملة للعناية بالسيارات من المنتجات إلى التدريب وخدمات التغليف المتميزة',
    'services.koch_title': 'منتجات كوخ كيمي',
    'services.koch_description': 'منتجات العناية بالسيارات الاحترافية من الشركة الرائدة في ألمانيا.',
    'services.koch_features.1': 'العناية المتميزة بالسيارات',
    'services.koch_features.2': 'التنظيف المهني',
    'services.koch_features.3': 'جودة رائدة في الصناعة',
    'services.koch_cta': 'عرض المنتجات',
    'services.courses_title': 'دورات التنظيف',
    'services.courses_description': 'برامج تدريبية متخصصة لتقنيات تنظيف وتلميع السيارات المهنية.',
    'services.courses_features.1': 'تدريب عملي',
    'services.courses_features.2': 'عبر الإنترنت وشخصياً',
    'services.courses_features.3': 'يشمل الشهادة',
    'services.courses_cta': 'سجل اليوم',
    'services.wrapping_title': 'خدمات إم تي رابس',
    'services.wrapping_description': 'خدمات تغليف السيارات المتميزة وتركيب الفينيل للحصول على إطلالة مذهلة.',
    'services.wrapping_features.1': 'تصاميم مخصصة',
    'services.wrapping_features.2': 'مواد متميزة',
    'services.wrapping_features.3': 'تركيب احترافي',
    'services.wrapping_cta': 'عرض المعرض',

    // Gallery/Wrapping Page
    'gallery.title': 'تغليف السيارات المهني',
    'gallery.subtitle': 'حوّل سيارتك باستخدام أفلام السيارات المتميزة. من تغييرات الألوان الكاملة إلى حلول الحماية، نقدم نتائج استثنائية بمواد رائدة في الصناعة.',
    'gallery.services_title': 'خدمات التغليف لدينا',
    'gallery.services_subtitle': 'اتصل بنا لمناقشة احتياجاتك من مجموعة متنوعة من خدمات تغليف السيارات والتنظيف المهنية',
    'gallery.professional_title': 'خدمات السيارات المهنية',
    'gallery.professional_description': 'نقدم مجموعة شاملة من خدمات تغليف السيارات والتنظيف. اتصل بنا لمناقشة الخدمة التي تناسب احتياجاتك وميزانيتك.',
    'gallery.wrapping_services': 'خدمات التغليف',
    'gallery.additional_services': 'خدمات إضافية',
    'gallery.why_choose': 'لماذا تختار خدماتنا؟',
    'gallery.premium_materials': 'مواد متميزة',
    'gallery.premium_materials_desc': 'أفلام السيارات الرائدة في الصناعة',
    'gallery.expert_installation': 'تركيب احترافي',
    'gallery.expert_installation_desc': 'فنيون محترفون معتمدون',
    'gallery.quality_guarantee': 'ضمان الجودة',
    'gallery.quality_guarantee_desc': 'ضمان على جميع الخدمات',
    'gallery.contact_quote': 'جاهز لتحويل سيارتك؟ اتصل بنا لمناقشة مشروعك والحصول على عرض أسعار مخصص.',
    'gallery.contact_for_quote': 'اتصل للحصول على عرض أسعار',
    'gallery.request_consultation': 'طلب استشارة',

    // Courses Page
    'courses.title': 'شهادة كوخ كيمي المهنية',
    'courses.subtitle': 'أتقن تقنيات التنظيف والتلميع في برنامج الشهادة الشامل لمدة 4 أيام، يُدرّس وفقاً لمعايير ومنهجيات كوخ كيمي المشهورة عالمياً.',
    'courses.intro_title': 'مقدمة الدورة',
    'courses.intro_subtitle': 'شاهد شرحنا المفصل لما ستتعلمه في دورة الشهادة هذه',
    'courses.course_title': 'دورة شهادة التنظيف والتلميع',
    'courses.course_description': 'برنامجنا الشامل لمدة 4 أيام يجمع بين التعلم التفاعلي والتدريب العملي، وينتهي بشهادة كوخ كيمي الرسمية المعترف بها في جميع أنحاء الصناعة.',
    'courses.what_learn': 'ما ستتعلمه',
    'courses.course_structure': 'هيكل الدورة لمدة 4 أيام',
    'courses.why_choose': 'لماذا تختار شهادة كوخ كيمي لدينا؟',
    'courses.enroll_now': 'سجل الآن',
    'courses.contact_details': 'اتصل للتفاصيل',
    
    // About Page
    'about.badge': 'حول إم تي رابس',
    'about.title': 'صياغة التميز في العناية بالسيارات',
    'about.subtitle': 'شريك التوزيع الرسمي لكوخ كيمي يجلب منتجات العناية بالسيارات الألمانية عالية الجودة والخبرة المهنية مباشرة إليك.',
    'about.story_title': 'قصتنا',
    'about.story_p1': 'نحن فخورون بكوننا شريك التوزيع الرسمي لكوخ كيمي، نجلب منتجات العناية بالسيارات الألمانية عالية الجودة مباشرة للمحترفين والهواة في جميع أنحاء المنطقة.',
    'about.story_p2': 'مع سنوات من الخبرة العملية في التنظيف والتلميع ومعالجة الأسطح، نحن لا نبيع المنتجات فقط — نحن نعيش الحرفة. فهمنا العميق للصناعة يسمح لنا بتقديم حلول مخصصة لكل مرحلة من مراحل العناية بالمركبات.',
    'about.story_p3': 'نحن أيضاً مؤسسو إم تي رابس، أحد الأسماء الرائدة في تغليف المركبات عالي الجودة والتخصيص. عملنا يتحدث عن نفسه — الدقة والإبداع والتنفيذ المتميز في كل سيارة نلمسها.',
    'about.koch_partner': 'شريك كوخ كيمي الرسمي',
    'about.koch_desc': 'منذ عام 1968، كانت كوخ كيمي المعيار للعناية المهنية بالسيارات. كشريكهم الرسمي، نجلب لك التميز الهندسي الألماني الأصيل.',
    'about.achievements': 'الإنجازات الرئيسية',
    'about.achievement_1': 'شريك كوخ كيمي الرسمي',
    'about.achievement_1_desc': 'موزع معتمد لمنتجات العناية بالسيارات الألمانية المتميزة',
    'about.achievement_2': '+500 عميل راضٍ',
    'about.achievement_2_desc': 'خدمة المحترفين والهواة في جميع أنحاء المنطقة',
    'about.achievement_3': 'التدريب المهني',
    'about.achievement_3_desc': 'دورات شاملة في التنظيف والتلميع',
    'about.achievement_4': 'خبرة إم تي رابس',
    'about.achievement_4_desc': 'خدمات رائدة في تغليف وتخصيص المركبات',
    'about.values_title': 'قيمنا',
    'about.value_precision': 'الدقة',
    'about.value_precision_desc': 'كل تفصيل مهم في عملنا وتقديم الخدمة',
    'about.value_innovation': 'الابتكار',
    'about.value_innovation_desc': 'البقاء في المقدمة بالمنتجات والتقنيات المتطورة',
    'about.value_quality': 'الجودة',
    'about.value_quality_desc': 'فقط أجود المنتجات والمواد المهندسة ألمانياً',
    'about.value_education': 'التعليم',
    'about.value_education_desc': 'تمكين المحترفين من خلال المعرفة والتدريب',
    
    // Contact Page
    'contact.badge': 'تواصل معنا',
    'contact.title': 'اتصل بـ MT Wraps',
    'contact.subtitle': 'جاهز لرفع مستوى العناية بمركبتك؟ تواصل مع فريقنا للمنتجات والتدريب أو خدمات التغليف المهنية.',
    'contact.form_title': 'أرسل لنا رسالة',
    'contact.form_subtitle': 'املأ النموذج أدناه وسنعاود الاتصال بك خلال 24 ساعة',
    'contact.name': 'الاسم الكامل',
    'contact.name_placeholder': 'أدخل اسمك الكامل',
    'contact.email': 'عنوان البريد الإلكتروني',
    'contact.email_placeholder': 'أدخل عنوان بريدك الإلكتروني',
    'contact.phone': 'رقم الهاتف',
    'contact.phone_placeholder': 'أدخل رقم هاتفك',
    'contact.company': 'الشركة',
    'contact.company_placeholder': 'أدخل اسم شركتك',
    'contact.service_interest': 'الاهتمام بالخدمة',
    'contact.service_interest_placeholder': 'اختر خدمة',
    'contact.subject': 'الموضوع',
    'contact.subject_placeholder': 'موضوع موجز لاستفسارك',
    'contact.message': 'الرسالة',
    'contact.message_placeholder': 'أخبرنا عن احتياجاتك...',
    'contact.send_message': 'إرسال الرسالة',
    'contact.sending': 'جاري الإرسال...',
    'contact.info_title': 'معلومات الاتصال',
    'contact.phone_title': 'الهاتف',
    'contact.phone_desc': 'اتصل بنا خلال ساعات العمل',
    'contact.email_title': 'البريد الإلكتروني',
    'contact.email_desc': 'نرد خلال 24 ساعة',
    'contact.location_title': 'الموقع',
    'contact.location_desc': 'قم بزيارة صالة العرض وورشة العمل',
    'contact.hours_title': 'ساعات العمل',
    'contact.hours_desc': 'الأحد إلى الخميس، اتصل للأوقات المحددة',
    'contact.success_title': 'تم إرسال الرسالة بنجاح!',
    'contact.success_desc': 'سنعاود الاتصال بك خلال 24 ساعة.',
    'contact.error_title': 'خطأ',
    'contact.error_desc': 'فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    
    // Products Page
    'products.search_placeholder': 'البحث عن المنتجات...',
    'products.all_categories': 'جميع الفئات',
    'products.no_products': 'لم يتم العثور على منتجات تطابق معاييرك.',
    'products.view_details': 'عرض التفاصيل',
    'products.add_to_cart': 'أضف إلى السلة',
    'products.in_stock': 'متوفر',
    'products.out_of_stock': 'غير متوفر',
    'products.price_tba': 'سيُعلن لاحقاً',
    'products.price_coming_soon': 'السعر قريباً',
    'products.lowest_price': 'من',
    'products.select_variant': 'اختر المتغير',
    'products.back_to_products': 'العودة إلى المنتجات',
    
    // Footer
    'footer.company_name': 'MTKcx',
    'footer.company_desc': 'الموزع الرسمي لكوخ كيمي يقدم منتجات العناية المتميزة بالسيارات والتدريب المهني وخدمات التغليف المتخصصة.',
    'footer.quick_links': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.service_1': 'العناية المهنية بالسيارات',
    'footer.service_2': 'تدريب التنظيف',
    'footer.service_3': 'تغليف السيارات',
    'footer.service_4': 'توزيع المنتجات',
    'footer.copyright': '© 2025 MT Wraps. جميع الحقوق محفوظة. | كوخ كيمي',
    
    // Stats
    'stats.products': 'منتج متميز',
    'stats.customers': 'عميل سعيد',
    'stats.experience': 'سنوات خبرة',

    // Common
    'common.learn_more': 'اعرف أكثر',
    'common.contact_us': 'اتصل بنا',
    'common.get_started': 'ابدأ الآن',
    'common.search': 'بحث',
    'common.professional_training': 'التدريب المهني',
    'common.mt_wraps_services': 'خدمات إم تي رابس',
    'common.official_partner': 'الشريك الرسمي لكوخ كيمي',
    'common.loading': 'جاري التحميل...',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تحرير',
    'common.delete': 'حذف',
    'common.close': 'إغلاق',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.view_all': 'عرض الكل',
    'common.show_more': 'عرض المزيد',
    'common.show_less': 'عرض أقل',
    'common.read_more': 'اقرأ المزيد',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.products': 'מוצרים',
    'nav.courses': 'קורסים',
    'nav.wrapping': 'עיטוף רכבים',
    'nav.about': 'אודות',
    'nav.contact': 'צור קשר',
    
    // Hero Section
    'hero.title': 'פתרונות טיפוח רכב והכשרה מתקדמים',
    'hero.subtitle': 'מפיץ רשמי של Koch-Chemie המציע מוצרי ניקיון מקצועיים, קורסי הכשרה מומחים ושירותי עיטוף רכבים מתקדמים.',
    'hero.cta.products': 'קנה מוצרים',
    'hero.cta.courses': 'צפה בקורסים',
    
    // Services Section
    'services.title': 'השירותים שלנו',
    'services.subtitle': 'פתרונות טיפוח רכב מקיפים מתוצרים להכשרה ושירותי עיטוף מתקדמים',
    'services.koch_title': 'מוצרי Koch-Chemie',
    'services.koch_description': 'מוצרי טיפוח רכב מקצועיים מהיצרן המוביל בגרמניה.',
    'services.koch_features.1': 'טיפוח רכב מתקדם',
    'services.koch_features.2': 'ניקיון מקצועי',
    'services.koch_features.3': 'איכות מובילה בתעשייה',
    'services.koch_cta': 'צפה במוצרים',
    'services.courses_title': 'קורסי ניקיון',
    'services.courses_description': 'תוכניות הכשרה מקצועיות לטכניקות ניקיון והברקת רכבים מקצועיים.',
    'services.courses_features.1': 'הכשרה מעשית',
    'services.courses_features.2': 'באינטרנט ובאופן אישי',
    'services.courses_features.3': 'כולל הסמכה',
    'services.courses_cta': 'הירשם היום',
    'services.wrapping_title': 'שירותי MT Wraps',
    'services.wrapping_description': 'שירותי עיטוף רכבים מתקדמים והתקנת ויניל למראה מדהים.',
    'services.wrapping_features.1': 'עיצובים מותאמים אישית',
    'services.wrapping_features.2': 'חומרים מתקדמים',
    'services.wrapping_features.3': 'התקנה מקצועית',
    'services.wrapping_cta': 'צפה בגלריה',

    // Gallery/Wrapping Page
    'gallery.title': 'עיטוף רכבים מקצועי',
    'gallery.subtitle': 'שנה את הרכב שלך עם סרטי רכב מתקדמים. משינויי צבע מלאים לפתרונות הגנה, אנו מספקים תוצאות יוצאות דופן עם חומרים מובילים בתעשייה.',
    'gallery.services_title': 'שירותי העיטוף שלנו',
    'gallery.services_subtitle': 'צור איתנו קשר לדיון על הצרכים שלך ממגוון שירותי עיטוף רכבים וניקיון מקצועיים',
    'gallery.professional_title': 'שירותי רכב מקצועיים',
    'gallery.professional_description': 'אנו מציעים מגוון מקיף של שירותי עיטוף רכבים וניקיון. צור איתנו קשר לדיון על השירות המתאים ביותר לצרכים ולתקציב שלך.',
    'gallery.wrapping_services': 'שירותי עיטוף',
    'gallery.additional_services': 'שירותים נוספים',
    'gallery.why_choose': 'למה לבחור בשירותים שלנו?',
    'gallery.premium_materials': 'חומרים מתקדמים',
    'gallery.premium_materials_desc': 'סרטי רכב מובילים בתעשייה',
    'gallery.expert_installation': 'התקנה מקצועית',
    'gallery.expert_installation_desc': 'טכנאים מקצועיים מוסמכים',
    'gallery.quality_guarantee': 'ערבות איכות',
    'gallery.quality_guarantee_desc': 'ערבות על כל השירותים',
    'gallery.contact_quote': 'מוכן לשנות את הרכב שלך? צור איתנו קשר לדיון על הפרויקט שלך ולקבלת הצעת מחיר מותאמת אישית.',
    'gallery.contact_for_quote': 'צור קשר להצעת מחיר',
    'gallery.request_consultation': 'בקש ייעוץ',

    // Courses Page
    'courses.title': 'הסמכת Koch Chemie מקצועית',
    'courses.subtitle': 'השלט בטכניקות ניקיון והברקה בתוכנית ההסמכה המקיפה שלנו למשך 4 ימים, הנלמדת לפי הסטנדרטים והמתודולוגיות הנודעות של Koch Chemie.',
    'courses.intro_title': 'מבוא לקורס',
    'courses.intro_subtitle': 'צפו בהסבר המפורט שלנו על מה שתלמדו בקורס ההסמכה הזה',
    'courses.course_title': 'קורס הסמכת ניקיון והברקה',
    'courses.course_description': 'התוכנית המקיפה שלנו למשך 4 ימים משלבת למידה אינטראקטיבית עם הכשרה מעשית, ומגיעה לשיא בהסמכת Koch Chemie רשמית המוכרת בכל התעשייה.',
    'courses.what_learn': 'מה תלמדו',
    'courses.course_structure': 'מבנה הקורס למשך 4 ימים',
    'courses.why_choose': 'למה לבחור בהסמכת Koch Chemie שלנו?',
    'courses.enroll_now': 'הירשם עכשיו',
    'courses.contact_details': 'צור קשר לפרטים',
    
    // About Page
    'about.badge': 'אודות MT Wraps',
    'about.title': 'יצירת מעולות בטיפוח רכב',
    'about.subtitle': 'שותף הפצה רשמי של Koch-Chemie המביא מוצרי טיפוח רכב גרמניים ברמה עולמית ומומחיות מקצועית ישירות אליכם.',
    'about.story_title': 'הסיפור שלנו',
    'about.story_p1': 'אנחנו גאים להיות שותפי הפצה רשמיים של Koch-Chemie, המביאים מוצרי טיפוח רכב גרמניים ברמה עולמית ישירות למקצועיים וחובבים ברחבי האזור.',
    'about.story_p2': 'עם שנים של ניסיון מעשי בניקיון, הברקה וטיפול במשטחים, אנחנו לא רק מוכרים מוצרים — אנחנו חיים את המקצוע. ההבנה העמוקה שלנו בתעשייה מאפשרת לנו לספק פתרונות מותאמים לכל שלב של טיפוח הרכב.',
    'about.story_p3': 'אנחנו גם מייסדי MT Wraps, אחד מהשמות המובילים בעיטוף רכבים איכותי והתאמה אישית. העבודה שלנו מדברת בעד עצמה — דיוק, יצירתיות וביצוע מעולה בכל רכב שאנחנו נוגעים בו.',
    'about.koch_partner': 'שותף רשמי של Koch-Chemie',
    'about.koch_desc': 'מאז 1968, Koch-Chemie הייתה הסטנדרט לטיפוח רכב מקצועי. כשותפיהם הרשמיים, אנחנו מביאים לכם מצוינות הנדסית גרמנית אותנטית.',
    'about.achievements': 'הישגים עיקריים',
    'about.achievement_1': 'שותף רשמי של Koch-Chemie',
    'about.achievement_1_desc': 'מפיץ מורשה של מוצרי טיפוח רכב גרמניים מעולים',
    'about.achievement_2': '+500 לקוחות מרוצים',
    'about.achievement_2_desc': 'משרתים מקצועיים וחובבים ברחבי האזור',
    'about.achievement_3': 'הכשרה מקצועית',
    'about.achievement_3_desc': 'קורסים מקיפים בניקיון והברקה',
    'about.achievement_4': 'מומחיות MT Wraps',
    'about.achievement_4_desc': 'שירותי עיטוף והתאמה אישית מובילים',
    'about.values_title': 'הערכים שלנו',
    'about.value_precision': 'דיוק',
    'about.value_precision_desc': 'כל פרט חשוב בעבודתנו ובמתן השירות',
    'about.value_innovation': 'חדשנות',
    'about.value_innovation_desc': 'להישאר בחזית עם מוצרים וטכניקות מתקדמות',
    'about.value_quality': 'איכות',
    'about.value_quality_desc': 'רק המוצרים והחומרים הגרמניים המעולים ביותר',
    'about.value_education': 'חינוך',
    'about.value_education_desc': 'העצמת מקצועיים באמצעות ידע והכשרה',
    
    // Contact Page
    'contact.badge': 'צור קשר',
    'contact.title': 'צור קשר עם MT Wraps',
    'contact.subtitle': 'מוכן להעלות את רמת הטיפוח ברכב שלך? צור קשר עם הצוות שלנו למוצרים, הכשרה או שירותי עיטוף מקצועיים.',
    'contact.form_title': 'שלח לנו הודעה',
    'contact.form_subtitle': 'מלא את הטופס למטה ונחזור אליך תוך 24 שעות',
    'contact.name': 'שם מלא',
    'contact.name_placeholder': 'הכנס את שמך המלא',
    'contact.email': 'כתובת אימייל',
    'contact.email_placeholder': 'הכנס את כתובת האימייל שלך',
    'contact.phone': 'מספר טלפון',
    'contact.phone_placeholder': 'הכנס את מספר הטלפון שלך',
    'contact.company': 'חברה',
    'contact.company_placeholder': 'הכנס את שם החברה שלך',
    'contact.service_interest': 'עניין בשירות',
    'contact.service_interest_placeholder': 'בחר שירות',
    'contact.subject': 'נושא',
    'contact.subject_placeholder': 'נושא קצר של הפנייה שלך',
    'contact.message': 'הודעה',
    'contact.message_placeholder': 'ספר לנו על הצרכים שלך...',
    'contact.send_message': 'שלח הודעה',
    'contact.sending': 'שולח...',
    'contact.info_title': 'פרטי קשר',
    'contact.phone_title': 'טלפון',
    'contact.phone_desc': 'התקשר אלינו בשעות העבודה',
    'contact.email_title': 'אימייל',
    'contact.email_desc': 'אנחנו מגיבים תוך 24 שעות',
    'contact.location_title': 'מיקום',
    'contact.location_desc': 'בקר בחדר התצוגה ובמוסך שלנו',
    'contact.hours_title': 'שעות עבודה',
    'contact.hours_desc': 'ראשון עד חמישי, צור קשר לשעות ספציפיות',
    'contact.success_title': 'ההודעה נשלחה בהצלחה!',
    'contact.success_desc': 'נחזור אליך תוך 24 שעות.',
    'contact.error_title': 'שגיאה',
    'contact.error_desc': 'שליחת ההודעה נכשלה. אנא נסה שוב.',
    
    // Products Page
    'products.search_placeholder': 'חפש מוצרים...',
    'products.all_categories': 'כל הקטגוריות',
    'products.no_products': 'לא נמצאו מוצרים התואמים לקריטריונים שלך.',
    'products.view_details': 'צפה בפרטים',
    'products.add_to_cart': 'הוסף לעגלה',
    'products.in_stock': 'במלאי',
    'products.out_of_stock': 'לא במלאי',
    'products.price_tba': 'TBA',
    'products.price_coming_soon': 'מחיר בקרוב',
    'products.lowest_price': 'החל מ',
    'products.select_variant': 'בחר וריאנט',
    'products.back_to_products': 'חזור למוצרים',
    
    // Footer
    'footer.company_name': 'MTKcx',
    'footer.company_desc': 'מפיץ רשמי של Koch-Chemie המספק מוצרי טיפוח רכב מעולים, הכשרה מקצועית ושירותי עיטוף מומחים.',
    'footer.quick_links': 'קישורים מהירים',
    'footer.services': 'שירותים',
    'footer.service_1': 'טיפוח רכב מקצועי',
    'footer.service_2': 'הכשרת ניקיון',
    'footer.service_3': 'עיטוף רכבים',
    'footer.service_4': 'הפצת מוצרים',
    'footer.copyright': '© 2025 MT Wraps. כל הזכויות שמורות. | Koch-Chemie',
    
    // Stats
    'stats.products': 'מוצרים מעולים',
    'stats.customers': 'לקוחות מרוצים',
    'stats.experience': 'שנות ניסיון',

    // Common
    'common.learn_more': 'למד עוד',
    'common.contact_us': 'צור קשר',
    'common.get_started': 'התחל',
    'common.search': 'חיפוש',
    'common.professional_training': 'הכשרה מקצועית',
    'common.mt_wraps_services': 'שירותי MT Wraps',
    'common.official_partner': 'שותף רשמי של Koch-Chemie',
    'common.loading': 'טוען...',
    'common.submit': 'שלח',
    'common.cancel': 'בטל',
    'common.save': 'שמור',
    'common.edit': 'ערוך',
    'common.delete': 'מחק',
    'common.close': 'סגור',
    'common.next': 'הבא',
    'common.previous': 'הקודם',
    'common.view_all': 'צפה בהכל',
    'common.show_more': 'הצג עוד',
    'common.show_less': 'הצג פחות',
    'common.read_more': 'קרא עוד',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    document.dir = lang === 'ar' || lang === 'he' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations[typeof currentLanguage]] || key;
  };

  const isRTL = currentLanguage === 'ar' || currentLanguage === 'he';

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};