-- Update category translations with proper Arabic and Hebrew translations
UPDATE categories SET 
  name_ar = CASE slug
    WHEN 'alkaline-cleaner' THEN 'منظفات قلوية'
    WHEN 'fragrances' THEN 'عطور'
    WHEN 'acid-cleaners-rim-cleaners' THEN 'منظفات حمضية ومنظفات الجنوط'
    WHEN 'leather-plastics-interior' THEN 'جلد وبلاستيك داخلي'
    WHEN 'solvents' THEN 'مذيبات'
    WHEN 'driers-conservers' THEN 'مجففات وحافظات'
    WHEN 'shampoos' THEN 'شامبو'
    WHEN 'glass-cleaners-water-processing' THEN 'منظفات الزجاج ومعالجة المياه'
    WHEN 'body-paint' THEN 'جسم وطلاء'
    WHEN 'rubber-plastics-external' THEN 'مطاط وبلاستيك خارجي'
    WHEN 'self-cleaning' THEN 'تنظيف ذاتي'
    WHEN 'foam-pads-applicators' THEN 'وسائد رغوية ومطبقات'
    WHEN 'microfiber-towels' THEN 'مناشف مايكروفايبر'
    WHEN 'sprayers' THEN 'رشاشات'
    WHEN 'polishing-coatings' THEN 'تلميع وطلاءات'
    WHEN 'exterior-cleaning' THEN 'تنظيف خارجي'
    WHEN 'interior-cleaning' THEN 'تنظيف داخلي'
    WHEN 'brushes-tools' THEN 'فرش وأدوات'
    WHEN 'tools-equipments' THEN 'أدوات ومعدات'
    WHEN 'sealants-protection' THEN 'مواد إغلاق وحماية'
    WHEN 'all-products' THEN 'جميع المنتجات'
    ELSE name_ar
  END,
  name_he = CASE slug
    WHEN 'alkaline-cleaner' THEN 'חומרי ניקוי אלקליים'
    WHEN 'fragrances' THEN 'ריחות'
    WHEN 'acid-cleaners-rim-cleaners' THEN 'חומרי ניקוי חומציים וניקוי חישוקים'
    WHEN 'leather-plastics-interior' THEN 'עור ופלסטיק פנימי'
    WHEN 'solvents' THEN 'ממיסים'
    WHEN 'driers-conservers' THEN 'מייבשים ושומרים'
    WHEN 'shampoos' THEN 'שמפו'
    WHEN 'glass-cleaners-water-processing' THEN 'מנקי זכוכית ועיבוד מים'
    WHEN 'body-paint' THEN 'גוף וצבע'
    WHEN 'rubber-plastics-external' THEN 'גומי ופלסטיק חיצוני'
    WHEN 'self-cleaning' THEN 'ניקוי עצמי'
    WHEN 'foam-pads-applicators' THEN 'רפידות קצף ומורחים'
    WHEN 'microfiber-towels' THEN 'מגבות מיקרופייבר'
    WHEN 'sprayers' THEN 'מרססים'
    WHEN 'polishing-coatings' THEN 'ליטוש וציפויים'
    WHEN 'exterior-cleaning' THEN 'ניקוי חיצוני'
    WHEN 'interior-cleaning' THEN 'ניקוי פנימי'
    WHEN 'brushes-tools' THEN 'מברשות וכלים'
    WHEN 'tools-equipments' THEN 'כלים וציוד'
    WHEN 'sealants-protection' THEN 'איטום והגנה'
    WHEN 'all-products' THEN 'כל המוצרים'
    ELSE name_he
  END;