// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdxychpgxptgxqvqiedj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkeHljaHBneHB0Z3hxdnFpZWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDk4NDAsImV4cCI6MjA2OTk4NTg0MH0.QgM0TfYVfE_FnM2amPHNI8_qXVtWVLvnLJ3vAE2m9JA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});